### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by ghost** [Wafelack/ByPass-Shell#4]
maybe consider using C function instead of the raw 'system' call
https://github.com/Wafelack/Wanager/blob/master/core/reinit.c
`    
system("del /f /q src\\* "); 
`
`     
system("del /f /q  target\\*");
`
Theres a few similarities over the whole repo! :wink:

**Comment by Wafelack** [comment]
Ok but i decided to make this project in Rustlang and you can see i used a function to run commands 👍 

But thx
